env:
  browser: true
  commonjs: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  experimentalObjectRestSpread: true
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  quotes:
    - error
    - single
  linebreak-style:
    - error
    - unix
  no-console: 0

